---
version: '2.4'

services:
  nginx:
    image: nginx:1.23
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/njs/:/etc/nginx/njs
    environment:
      REACT_APP_SUBTITLE: "Testing NJS Subtitle"
    env_file:
      - ./.env.local
    ports:
      - 3000:80
